export const CHAT_LOAD = Symbol('CHAT_LOAD')
export const CHAT_LOAD_SUCCESS = Symbol('CHAT_LOAD_SUCCESS')
export const CHAT_LOAD_FAILURE = Symbol('CHAT_LOAD_FAILURE')

export const CHAT_SEND_MESSAGE = Symbol('CHAT_SEND_MESSAGE')
export const CHAT_SEND_MESSAGE_SUCCESS = Symbol('CHAT_SEND_MESSAGE_SUCCESS')
export const CHAT_SEND_MESSAGE_FAILURE = Symbol('CHAT_SEND_MESSAGE_FAILURE')

export const CHAT_RECEIVE_MESSAGE = Symbol('CHAT_RECEIVE_MESSAGE')

export const CHAT_REMOVE_MESSAGE = Symbol('CHAT_REMOVE_MESSAGE')
export const CHAT_REMOVE_MESSAGE_SUCCESS = Symbol('CHAT_REMOVE_MESSAGE_SUCCESS')
export const CHAT_REMOVE_MESSAGE_FAILURE = Symbol('CHAT_REMOVE_MESSAGE_FAILURE')
