export const COINFLIP_LOAD_HISTORY = Symbol('COINFLIP_LOAD_HISTORY')
export const COINFLIP_LOAD_HISTORY_SUCCESS = Symbol('COINFLIP_LOAD_HISTORY_SUCCESS')
export const COINFLIP_LOAD_HISTORY_FAILURE = Symbol('COINFLIP_LOAD_HISTORY_FAILURE')

export const ROULETTE_LOAD_HISTORY = Symbol('ROULETTE_LOAD_HISTORY')
export const ROULETTE_LOAD_HISTORY_SUCCESS = Symbol('ROULETTE_LOAD_HISTORY_SUCCESS')
export const ROULETTE_LOAD_HISTORY_FAILURE = Symbol('ROULETTE_LOAD_HISTORY_FAILURE')
