export const COINFLIP_LOAD_HISTORY = Symbol('COINFLIP_LOAD_HISTORY')
export const COINFLIP_LOAD_HISTORY_SUCCESS = Symbol('COINFLIP_LOAD_HISTORY_SUCCESS')
export const COINFLIP_LOAD_HISTORY_FAILURE = Symbol('COINFLIP_LOAD_HISTORY_FAILURE')
