export const COINFLIP_LOAD_HISTORY = Symbol('COINFLIP_LOAD_HISTORY')
export const COINFLIP_LOAD_HISTORY_SUCCESS = Symbol('COINFLIP_LOAD_HISTORY_SUCCESS')
export const COINFLIP_LOAD_HISTORY_FAILURE = Symbol('COINFLIP_LOAD_HISTORY_FAILURE')

export const ROULETTE_LOAD_HISTORY = Symbol('ROULETTE_LOAD_HISTORY')
export const ROULETTE_LOAD_HISTORY_SUCCESS = Symbol('ROULETTE_LOAD_HISTORY_SUCCESS')
export const ROULETTE_LOAD_HISTORY_FAILURE = Symbol('ROULETTE_LOAD_HISTORY_FAILURE')

export const ROULETTE_ADD_HISTORY_GAME = Symbol('ROULETTE_ADD_HISTORY_GAME')

export const ROULETTE_JOIN_GAME = Symbol('ROULETTE_JOIN_GAME')
export const ROULETTE_JOIN_GAME_SUCCESS = Symbol('ROULETTE_JOIN_GAME_SUCCESS')
export const ROULETTE_JOIN_GAME_FAILURE = Symbol('ROULETTE_JOIN_GAME_FAILURE')
