export const USER_LOAD_INVENTORY = Symbol('USER_LOAD_INVENTORY')
export const USER_LOAD_INVENTORY_SUCCESS = Symbol('USER_LOAD_INVENTORY_SUCCESS')
export const USER_LOAD_INVENTORY_FAILURE = Symbol('USER_LOAD_INVENTORY_FAILURE')
