export const USER_LOAD_INVENTORY = Symbol('USER_LOAD_INVENTORY')
export const USER_LOAD_INVENTORY_SUCCESS = Symbol('USER_LOAD_INVENTORY_SUCCESS')
export const USER_LOAD_INVENTORY_FAILURE = Symbol('USER_LOAD_INVENTORY_FAILURE')

export const USER_CREATE_AFFILIATE_CODE = Symbol('USER_CREATE_AFFILIATE_CODE')
export const USER_CREATE_AFFILIATE_CODE_SUCCESS = Symbol('USER_CREATE_AFFILIATE_CODE_SUCCESS')
export const USER_CREATE_AFFILIATE_CODE_FAILURE = Symbol('USER_CREATE_AFFILIATE_CODE_FAILURE')

export const USER_REDEEM_AFFILIATE_CODE = Symbol('USER_REDEEM_AFFILIATE_CODE')
export const USER_REDEEM_AFFILIATE_CODE_SUCCESS = Symbol('USER_REDEEM_AFFILIATE_CODE_SUCCESS')
export const USER_REDEEM_AFFILIATE_CODE_FAILURE = Symbol('USER_REDEEM_AFFILIATE_CODE_FAILURE')

export const USER_LOAD_AFFILIATE_STATS = Symbol('USER_LOAD_AFFILIATE_STATS')
export const USER_LOAD_AFFILIATE_STATS_SUCCESS = Symbol('USER_LOAD_AFFILIATE_STATS_SUCCESS')
export const USER_LOAD_AFFILIATE_STATS_FAILURE = Symbol('USER_LOAD_AFFILIATE_STATS_FAILURE')

export const USER_CLAIM_AFFILIATE_BALANCE = Symbol('USER_CLAIM_AFFILIATE_BALANCE')
export const USER_CLAIM_AFFILIATE_BALANCE_SUCCESS = Symbol('USER_CLAIM_AFFILIATE_BALANCE_SUCCESS')
export const USER_CLAIM_AFFILIATE_BALANCE_FAILURE = Symbol('USER_CLAIM_AFFILIATE_BALANCE_FAILURE')
